In [19]:
import numpy as np
import sklearn


In [13]:
my_array = np.array([[1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16]])

print(my_array)
print(my_array.ndim)
print(type(my_array))
print(my_array.shape)
print(my_array.size)

[[ 1  4  5  6]
 [ 7  8  9 10]
 [11 12 14 16]]
2
<class 'numpy.ndarray'>
(3, 4)
12


In [14]:
my_arr = np.array([[1, 2 , 3 , 4], [5, 6, 7, 8]])
print(np.resize(my_arr, (3,4 )))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


In [15]:
my_first_arr = np.array([1,2,3,4,5,6,7,8])
my_new_arr = np.reshape(my_first_arr, (2,4))
print(my_new_arr)
print(my_first_arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [16]:
apple = np.array([1 , 8 , 23 , 3 , 18 , 91 , 7 , 15])
apple_slice = apple[1:4]
print(apple_slice)
print(apple)
apple_slice[1]=99999
print(apple_slice)
print(apple)

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]
[    8 99999     3]
[    1     8 99999     3    18    91     7    15]


In [18]:
X_stat = np.array([[1,2,3],[4 ,-5,6]])
print(X_stat.mean())
print(X_stat.std())
print(X_stat.var())
print(X_stat.min())
print(X_stat.max())
print(X_stat.sum())
print(X_stat.prod())


1.8333333333333333
3.435921354681384
11.805555555555557
-5
6
11
-720


In [20]:
from sklearn.datasets import load_sample_image
china = load_sample_image('china.jpg')
portions = china[120:250,110:230]
print(portions.shape)

(130, 120, 3)
